# Generated by Django 4.2.6 on 2023-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('tipoCliente', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('empresarial', 'Empresarial')], max_length=20)),
            ],
        ),
    ]
